version: "3.8"

services:
  web:
    build: .
    container_name: php-apache
    volumes:
      - ./web:/var/www/html
      - ./web/.htaccess:/var/www/html/.htaccess
    ports:
      - "80:80"
    networks:
      - my_network

  db:
    image: mysql:8.0
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: merrychristmas
      MYSQL_DATABASE: iso_db
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: merrychristmas
      MYSQL_ROOT_PASSWORD: merrychristmas
    ports:
      - "8080:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
