<!-- jQuery Frameworks
    ============================================= -->
	<script src="<?=rootURL();?>assets/js/jquery-3.7.0.min.js"></script>
	<script src="<?=rootURL();?>assets/js/popper.min.js"></script>
	<script src="<?=rootURL();?>assets/js/bootstrap.min.js"></script>
	<script src="<?=rootURL();?>assets/js/bsnav.min.js"></script>
	<script src="<?=rootURL();?>assets/js/jquery.magnific-popup.min.js"></script>
	<script src="<?=rootURL();?>assets/js/isotope.pkgd.min.js"></script>
	<script src="<?=rootURL();?>assets/js/imagesloaded.pkgd.min.js"></script>
	<script src="<?=rootURL();?>assets/js/wow.min.js"></script>
	<script src="<?=rootURL();?>assets/js/count-to.js"></script>
	<script src="<?=rootURL();?>assets/js/progress-bar.min.js"></script>
	<script src="<?=rootURL();?>assets/js/jquery.easypiechart.js"></script>
	<script src="<?=rootURL();?>assets/js/typed.js"></script>
	<script src="<?=rootURL();?>assets/js/YTPlayer.min.js"></script>
	<script src="<?=rootURL();?>assets/js/jquery.appear.js"></script>
	<script src="<?=rootURL();?>assets/js/jquery.easing.min.js"></script>
	<script src="<?=rootURL();?>assets/js/swiper-bundle.min.js"></script>
	<script src="<?=rootURL();?>assets/js/active-class.js"></script>
	<script src="<?=rootURL();?>assets/js/jquery-ui.min.js"></script>
	<script src="<?=rootURL();?>assets/js/main.js"></script>